<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\lib\Images\banner.png" />
    <None Include="wwwroot\lib\Images\bg.png" />
    <None Include="wwwroot\lib\Images\logo.png" />
    <None Include="wwwroot\lib\Images\sabc-logo.png" />
  </ItemGroup>

</Project>
