// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SABC_Phase2.Data;

#nullable disable

namespace SABC_Phase2.Migrations
{
    [DbContext(typeof(Phase2Context))]
    [Migration("20250709120557_Push1")]
    partial class Push1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SABC_Phase2.Models.OVRS.ApplicationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenderApplicationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenderApplicationId");

                    b.ToTable("ApplicationDocuments");
                });

            modelBuilder.Entity("SABC_Phase2.Models.OVRS.OVRS_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LegacyUserId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SABC_Phase2.Models.OVRS.TenderApplicationDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OVRS_UserId")
                        .HasColumnType("int");

                    b.Property<int?>("TenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OVRS_UserId");

                    b.ToTable("TenderApplicationDrafts");
                });

            modelBuilder.Entity("SABC_Phase2.Models.OVRS.TenderApplicationDraftDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenderApplicationDraftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenderApplicationDraftId");

                    b.ToTable("TenderApplicationDraftDocuments");
                });

            modelBuilder.Entity("SABC_Phase2.Models.OVRS.TenderApplications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateApplied")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OVRS_UserId")
                        .HasColumnType("int");

                    b.Property<int>("TenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OVRS_UserId");

                    b.HasIndex("TenderId");

                    b.ToTable("Applied_For_Tenders");
                });

            modelBuilder.Entity("SABC_Phase2.Models.Tender.ScheduledTender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledPublishDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScheduledTenders");
                });

            modelBuilder.Entity("SABC_Phase2.Models.Tender.ScheduledTenderDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduledTenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledTenderId");

                    b.ToTable("ScheduledTendersDocuments");
                });

            modelBuilder.Entity("SABC_Phase2.Models.Tender.Tender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AwardedTender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenders");
                });

            modelBuilder.Entity("SABC_Phase2.Models.Tender.TenderDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenderId");

                    b.ToTable("TenderDocuments");
                });

            modelBuilder.Entity("SABC_Phase2.Models.Tender.TenderDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenderType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TenderAdminsDraft");
                });

            modelBuilder.Entity("SABC_Phase2.Models.Tender.TenderDraftDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenderDraftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenderDraftId");

                    b.ToTable("TenderAdminsDraftDocuments");
                });

            modelBuilder.Entity("SABC_Phase2.Models.OVRS.ApplicationDocument", b =>
                {
                    b.HasOne("SABC_Phase2.Models.OVRS.TenderApplications", "TenderApplication")
                        .WithMany("Documents")
                        .HasForeignKey("TenderApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderApplication");
                });

            modelBuilder.Entity("SABC_Phase2.Models.OVRS.TenderApplicationDraft", b =>
                {
                    b.HasOne("SABC_Phase2.Models.OVRS.OVRS_User", "OVRS_User")
                        .WithMany()
                        .HasForeignKey("OVRS_UserId");

                    b.Navigation("OVRS_User");
                });

            modelBuilder.Entity("SABC_Phase2.Models.OVRS.TenderApplicationDraftDocument", b =>
                {
                    b.HasOne("SABC_Phase2.Models.OVRS.TenderApplicationDraft", "TenderApplicationDraft")
                        .WithMany("Documents")
                        .HasForeignKey("TenderApplicationDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderApplicationDraft");
                });

            modelBuilder.Entity("SABC_Phase2.Models.OVRS.TenderApplications", b =>
                {
                    b.HasOne("SABC_Phase2.Models.OVRS.OVRS_User", "OVRS_User")
                        .WithMany()
                        .HasForeignKey("OVRS_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SABC_Phase2.Models.Tender.Tender", "Tender")
                        .WithMany()
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OVRS_User");

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("SABC_Phase2.Models.Tender.ScheduledTenderDocument", b =>
                {
                    b.HasOne("SABC_Phase2.Models.Tender.ScheduledTender", "ScheduledTender")
                        .WithMany("Documents")
                        .HasForeignKey("ScheduledTenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledTender");
                });

            modelBuilder.Entity("SABC_Phase2.Models.Tender.TenderDocument", b =>
                {
                    b.HasOne("SABC_Phase2.Models.Tender.Tender", "Tender")
                        .WithMany("Documents")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("SABC_Phase2.Models.Tender.TenderDraftDocument", b =>
                {
                    b.HasOne("SABC_Phase2.Models.Tender.TenderDraft", "TenderDraft")
                        .WithMany("Documents")
                        .HasForeignKey("TenderDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderDraft");
                });

            modelBuilder.Entity("SABC_Phase2.Models.OVRS.TenderApplicationDraft", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("SABC_Phase2.Models.OVRS.TenderApplications", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("SABC_Phase2.Models.Tender.ScheduledTender", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("SABC_Phase2.Models.Tender.Tender", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("SABC_Phase2.Models.Tender.TenderDraft", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
